### ISSUE TITLE
Suggested Resource Addition - Hockey

### ISSUE THREAD

**Issue by piyer97** [cran-task-views/SportsAnalytics#3]
Suggesting the addition of the hockeyR package created by Dan Morse that offers functions to scrape and clean NHL data from NHL.com and Hockey-Reference.com

https://github.com/danmorse314/hockeyR

**Comment by qntkhvn** [comment]
`hockeyR` is back on CRAN and has been added [d5af880](https://github.com/cran-task-views/SportsAnalytics/commit/d5af880df3700070ebbbaede5c82b959d6e04f4f).
